//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoeItemInfo.Data.ModelTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoeItemInfo.Data.ModelTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;numTabs&quot;:88,&quot;items&quot;:[{&quot;verified&quot;:false,&quot;w&quot;:2,&quot;h&quot;:2,&quot;icon&quot;:&quot;http:\/\/webcdn.pathofexile.com\/image\/Art\/2DItems\/Armours\/Boots\/BootsStrDex2.png?scale=1&amp;w=2&amp;h=2&amp;v=bdfb39d9a0b60c4ac542bedd8ff06e083&quot;,&quot;support&quot;:true,&quot;league&quot;:&quot;Standard&quot;,&quot;sockets&quot;:[{&quot;group&quot;:0,&quot;attr&quot;:&quot;S&quot;},{&quot;group&quot;:0,&quot;attr&quot;:&quot;D&quot;}],&quot;name&quot;:&quot;Torment Sole&quot;,&quot;typeLine&quot;:&quot;Hydrascale Boots&quot;,&quot;identified&quot;:true,&quot;corrupted&quot;:false,&quot;properties&quot;:[{&quot;name&quot;:&quot;Armour&quot;,&quot;values&quot;:[[&quot;128&quot;,1]],&quot;displayMode&quot;:0},{&quot;name&quot;:&quot;Evasion Rating&quot;,&quot;values&quot;:[[&quot;135&quot;,1]],&quot;displayMode&quot;:0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FullStashTab {
            get {
                return ResourceManager.GetString("FullStashTab", resourceCulture);
            }
        }
    }
}
